export enum PlaceCategory {
  KNOWLEDGE = 'KNOWLEDGE',
  FAITH = 'FAITH',
  NATURE = 'NATURE',
  COMMERCE = 'COMMERCE',
  FITNESS = 'FITNESS',
  COMMUNITY = 'COMMUNITY',
  CRAFT = 'CRAFT',
  HEALTH = 'HEALTH',
  ARTS = 'ARTS',
  HISTORIC = 'HISTORIC',
}
