services:
  database:
    image: postgres:17.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
