services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - /app/node_modules/
            - /app/dist/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
          ignore:
            - /app/node_modules/
            - /app/dist/
            - /app/build/ # Including build directory to ignore

  db:
    image: postgres:17.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
