services:
  database:
    image: postgres:17.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
