
FROM node:22 AS builder

WORKDIR /app

COPY package*.json package-lock.json* ./ 
RUN npm install --only=development 

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "run", "start:dev"]